#!/usr/bin/env bash
# nd installer — interactive, Omarchy-style. One command from a fresh NixOS login:
#
#   curl -sL https://raw.githubusercontent.com/kraeki/nd-dotfiles/main/install.sh | bash
#
# Asks which machine this is (or probes the hardware and generates a new
# hosts/<name>/ for it), symlinks the dotfiles, and rebuilds. Idempotent:
# safe to re-run to update an existing setup.
#
# Non-interactive use: set ND_HOST to an existing host to skip all prompts
# (plus ND_DIR / ND_REPO to override paths). Prompts need a terminal; the
# script grabs /dev/tty so it survives `curl | sh`.
set -euo pipefail

ND_REPO="${ND_REPO:-https://github.com/kraeki/nd-dotfiles.git}"
ND_DIR="${ND_DIR:-$HOME/work/nd-dotfiles}"
ND_HOST="${ND_HOST:-}"

TEAL=$'\033[36m'; DIM=$'\033[2m'; BOLD=$'\033[1m'; RED=$'\033[31m'; RESET=$'\033[0m'

banner() {
  printf '%s' "$TEAL"
  cat <<'LOGO'

  ┌─┐┌─┐
  │ ││ │  ndos
  └─┘└─┘
LOGO
  printf '%s' "$RESET"
  printf '  %sNixOS + Hyprland, declarative all the way down%s\n\n' "$DIM" "$RESET"
}

say() { printf '%s[nd]%s %s\n' "$TEAL" "$RESET" "$*"; }
die() { printf '%s[nd]%s %s\n' "$RED" "$RESET" "$*" >&2; exit 1; }

# Tools may not exist yet on a fresh install — fall back to running them out
# of nixpkgs without installing anything (gum is what draws the prompts).
run() {
  local tool="$1"; shift
  if command -v "$tool" >/dev/null 2>&1; then
    "$tool" "$@"
  else
    nix --extra-experimental-features 'nix-command flakes' \
      shell "nixpkgs#$tool" -c "$tool" "$@"
  fi
}
ui() { run gum "$@"; }

banner
[ -e /etc/NIXOS ] || die "This installer expects NixOS. For other setups, clone the repo and run 'make' for dotfiles only."

# `curl | sh` leaves stdin on the pipe; reattach to the terminal for prompts.
if [ ! -t 0 ]; then
  if [ -r /dev/tty ]; then exec </dev/tty; else
    [ -n "$ND_HOST" ] || die "No terminal for prompts. Set ND_HOST=<host> for a non-interactive install."
  fi
fi

## Get the repo
if [ -d "$ND_DIR/.git" ]; then
  say "Updating existing checkout at $ND_DIR"
  run git -C "$ND_DIR" pull --ff-only
else
  say "Cloning $ND_REPO to $ND_DIR"
  mkdir -p "$(dirname "$ND_DIR")"
  run git clone "$ND_REPO" "$ND_DIR"
fi

## Which machine is this?
NEW_HOST=0
if [ -z "$ND_HOST" ]; then
  mapfile -t hosts < <(find "$ND_DIR/hosts" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | sort)
  choice=$(ui choose --header "Which machine is this?" "${hosts[@]}" "✚ new machine (probe hardware)")
  case "$choice" in
    "✚ new machine"*) NEW_HOST=1 ;;
    *) ND_HOST="$choice" ;;
  esac
fi

## New machine: probe hardware, generate a thin host on top of the nd profile
if [ "$NEW_HOST" = 1 ]; then
  ND_HOST=$(ui input --header "Hostname for this machine" --placeholder "e.g. desktop" --value "")
  [ -n "$ND_HOST" ] || die "A hostname is required."
  [ -d "$ND_DIR/hosts/$ND_HOST" ] && die "hosts/$ND_HOST already exists — pick it from the list instead."
  username=$(ui input --header "Your username" --value "${SUDO_USER:-${USER:-kraeki}}")
  fullname=$(ui input --header "Your full name (for the user account)" --value "")
  release=$(nixos-version | grep -oE '^[0-9]+\.[0-9]+' || echo "25.05")

  say "Probing hardware (nixos-generate-config)"
  mkdir -p "$ND_DIR/hosts/$ND_HOST"
  sudo nixos-generate-config --show-hardware-config > "$ND_DIR/hosts/$ND_HOST/hardware-configuration.nix"

  cat > "$ND_DIR/hosts/$ND_HOST/default.nix" <<'EOF'
# @HOST@ — generated by install.sh. This file holds only what is true of
# THIS machine; everything identity-shaped comes from modules/nixos via
# `nd.enable = true`. Grow it with hardware truth (microcode, kernel
# quirks, vendor tools) as you learn this machine — see hosts/naptop for
# what that looks like.
{ config, pkgs, inputs, ... }:

{
  imports = [
    ./hardware-configuration.nix
    # If nixos-hardware has a profile for this machine, add it here:
    # inputs.nixos-hardware.nixosModules.<your-machine>
  ];

  # The nd profile (modules/nixos), whole thing on.
  nd.enable = true;

  networking.hostName = "@HOST@";

  # Bootloader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  users.users.@USER@ = {
    isNormalUser = true;
    description = "@FULLNAME@";
    extraGroups = [ "networkmanager" "wheel" "docker" "video" "render" ];
    shell = pkgs.zsh;
  };

  home-manager = {
    useGlobalPkgs = true;
    useUserPackages = true;
    extraSpecialArgs = { inherit inputs; };
    users.@USER@ = import ../../users/@USER@/home.nix;
  };

  # NixOS release at first install of this machine — do not bump on upgrades.
  system.stateVersion = "@RELEASE@";
}
EOF
  sed -i "s/@HOST@/$ND_HOST/g; s/@USER@/$username/g; s/@FULLNAME@/$fullname/g; s/@RELEASE@/$release/g" \
    "$ND_DIR/hosts/$ND_HOST/default.nix"

  if [ ! -f "$ND_DIR/users/$username/home.nix" ]; then
    say "Creating a starter home config for '$username'"
    mkdir -p "$ND_DIR/users/$username"
    cat > "$ND_DIR/users/$username/home.nix" <<'EOF'
# @USER@'s home: the nd home profile plus personal packages and aliases.
# Generated by install.sh — add your packages here (see users/kraeki/home.nix
# for a fuller example).
{ config, pkgs, inputs, ... }:

{
  imports = [ ../../modules/home ];

  # The nd home profile (modules/home), whole thing on.
  nd.enable = true;

  home.username = "@USER@";
  home.homeDirectory = "/home/@USER@";
  home.stateVersion = "@RELEASE@";

  programs.home-manager.enable = true;

  home.packages = with pkgs; [
    firefox
  ];
}
EOF
    sed -i "s/@USER@/$username/g; s/@RELEASE@/$release/g" "$ND_DIR/users/$username/home.nix"
  fi

  # Flakes only see git-tracked files; without this the new host is invisible.
  run git -C "$ND_DIR" add "hosts/$ND_HOST" "users/$username"
  say "Generated hosts/$ND_HOST (staged in git — commit & push it once you're happy)"
fi

## Dotfiles
say "Symlinking dotfiles into \$HOME (stow)"
(cd "$ND_DIR/dotfiles" && run stow --target="$HOME" --restow -- */)

# Hyprland expects the script directory to exist (see CLAUDE.md).
mkdir -p "$HOME/.local/share/bin"

## Build & switch
echo
ui confirm "Build and switch to the '$ND_HOST' system now? (first run downloads/compiles a lot)" \
  || { say "Skipped. Later: sudo nixos-rebuild switch --flake $ND_DIR#$ND_HOST"; exit 0; }

sudo env NIX_CONFIG="experimental-features = nix-command flakes" \
  nixos-rebuild switch --flake "$ND_DIR#$ND_HOST"

echo
say "Done. Log out/in (or reboot) and start the desktop with: ${BOLD}hypr${RESET}"
[ "$NEW_HOST" = 1 ] && say "Remember to commit & push hosts/$ND_HOST so this machine is reproducible."
