# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-a5d69def-eaab-4b87-ab50-da0237d9abfa";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-a5d69def-eaab-4b87-ab50-da0237d9abfa".device = "/dev/disk/by-uuid/a5d69def-eaab-4b87-ab50-da0237d9abfa";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/60E1-7ED9";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-ce375174-c66d-4587-bf7c-acf70aa63c2f"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
