# nd-install — runs on the nd ISO. Wifi → GitHub auth → clone → pick or
# generate a host → disko partitioning → nixos-install → reboot.
# (Wrapped by writeShellScriptBin in iso/default.nix.)
set -euo pipefail

ND_REPO="${ND_REPO:-https://github.com/kraeki/nd-dotfiles.git}"
ND_DIR="${ND_DIR:-/root/nd-dotfiles}"

TEAL=$'\033[36m'; DIM=$'\033[2m'; BOLD=$'\033[1m'; RED=$'\033[31m'; RESET=$'\033[0m'
say() { printf '%s[nd]%s %s\n' "$TEAL" "$RESET" "$*"; }
die() { printf '%s[nd]%s %s\n' "$RED" "$RESET" "$*" >&2; exit 1; }

[ "$(id -u)" = 0 ] || exec sudo ND_REPO="$ND_REPO" ND_DIR="$ND_DIR" "$0" "$@"

printf '%s' "$TEAL"
cat <<'LOGO'

  ┌─┐┌─┐
  │ ││ │  ndos installer
  └─┘└─┘
LOGO
printf '%s' "$RESET"
printf '  %sthis will ERASE a disk on this machine — nothing happens before a final confirmation%s\n\n' "$DIM" "$RESET"

## 1. Network
if ! nm-online -q -t 5 2>/dev/null; then
  say "No network. Pick a wifi network:"
  nmcli device wifi rescan 2>/dev/null || true; sleep 2
  ssid=$(nmcli -t -f SSID device wifi list | grep -v '^$' | sort -u | gum choose --header "Wifi network")
  pass=$(gum input --password --header "Passphrase for $ssid")
  nmcli device wifi connect "$ssid" password "$pass"
  nm-online -q -t 30 || die "Still offline — check the connection and re-run nd-install."
fi

## 2. GitHub (private repo → device flow: code on screen, confirm on phone)
if ! gh auth status >/dev/null 2>&1; then
  say "Authenticate with GitHub (repo is private). A one-time code will appear —"
  say "open the URL on your phone and enter it."
  gh auth login --hostname github.com --git-protocol https
fi
gh auth setup-git

## 3. Repo
if [ ! -d "$ND_DIR/.git" ]; then
  say "Cloning $ND_REPO"
  git clone "$ND_REPO" "$ND_DIR"
fi

## 4. Which machine?
mapfile -t hosts < <(find "$ND_DIR/hosts" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | sort)
choice=$(gum choose --header "Install which machine?" "${hosts[@]}" "✚ new machine (probe hardware)")

nixeval() { nix --extra-experimental-features 'nix-command flakes' eval "$@"; }

if [ "$choice" = "✚ new machine (probe hardware)" ]; then
  host=$(gum input --header "Hostname for this machine" --placeholder "e.g. desktop")
  [ -n "$host" ] || die "A hostname is required."
  [ -d "$ND_DIR/hosts/$host" ] && die "hosts/$host already exists — pick it from the list instead."
  username=$(gum input --header "Your username" --value "kraeki")
  fullname=$(gum input --header "Your full name" --value "")
  release=$(nixos-version | grep -oE '^[0-9]+\.[0-9]+' || echo "25.05")

  # Target disk
  mapfile -t disks < <(lsblk -dno NAME,SIZE,MODEL --sort NAME | awk '$1 !~ /^(loop|sr|ram)/ {print "/dev/"$0}')
  disk=$(printf '%s\n' "${disks[@]}" | gum choose --header "Install to which disk? (WILL BE ERASED)" | awk '{print $1}')

  say "Probing hardware"
  mkdir -p "$ND_DIR/hosts/$host"
  nixos-generate-config --no-filesystems --show-hardware-config \
    > "$ND_DIR/hosts/$host/hardware-configuration.nix"

  # disko owns the mounts on a generated host (same layout as naptop:
  # GPT, 1G ESP, LUKS2 → ext4, no swap).
  sed -e "s|/dev/nvme0n1|$disk|" \
      -e '/disko.enableConfig = false;/d' \
      -e '/^#/d' \
      "$ND_DIR/hosts/naptop/disko.nix" > "$ND_DIR/hosts/$host/disko.nix"

  cat > "$ND_DIR/hosts/$host/default.nix" <<EOF
# $host — generated by the nd ISO installer. Hardware truth only;
# identity comes from modules/nixos via nd.enable.
{ config, pkgs, inputs, ... }:

{
  imports = [
    ./hardware-configuration.nix
    inputs.disko.nixosModules.disko
    ./disko.nix
  ];

  nd.enable = true;

  networking.hostName = "$host";

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  users.users.$username = {
    isNormalUser = true;
    description = "$fullname";
    extraGroups = [ "networkmanager" "wheel" "docker" "video" "render" ];
    shell = pkgs.zsh;
  };

  home-manager = {
    useGlobalPkgs = true;
    useUserPackages = true;
    extraSpecialArgs = { inherit inputs; };
    users.$username = import ../../users/$username/home.nix;
  };

  system.stateVersion = "$release";
}
EOF

  if [ ! -f "$ND_DIR/users/$username/home.nix" ]; then
    mkdir -p "$ND_DIR/users/$username"
    cat > "$ND_DIR/users/$username/home.nix" <<EOF
# $username's home — generated by the nd ISO installer. Add your packages
# here (see users/kraeki/home.nix for a fuller example).
{ config, pkgs, inputs, ... }:

{
  imports = [ ../../modules/home ];
  nd.enable = true;
  home.username = "$username";
  home.homeDirectory = "/home/$username";
  home.stateVersion = "$release";
  programs.home-manager.enable = true;
  home.packages = with pkgs; [ firefox ];
}
EOF
  fi
  git -C "$ND_DIR" add "hosts/$host" "users/$username"
else
  host=$choice
  # An existing host must let disko own its mounts, or the fresh partitions
  # (new UUIDs) won't match its hardware-configuration.nix.
  if [ "$(nixeval "$ND_DIR#nixosConfigurations.$host.config.disko.enableConfig" 2>/dev/null)" != "true" ]; then
    die "hosts/$host still mounts via hardware-configuration.nix UUIDs. Follow the 'Bare-metal reinstall' flip steps in the README (enableConfig + --no-filesystems), push, and re-run."
  fi
  disk=$(nixeval --raw "$ND_DIR#nixosConfigurations.$host.config.disko.devices.disk.main.device")
  username=$(nixeval --raw "$ND_DIR#nixosConfigurations.$host.config" --apply \
    'c: builtins.head (builtins.filter (n: c.users.users.${n}.isNormalUser or false) (builtins.attrNames c.users.users))' 2>/dev/null) \
    || username=$(gum input --header "Username on $host")
fi

## 5. LUKS passphrase (consumed by disko at format time)
p1=$(gum input --password --header "Disk encryption passphrase")
p2=$(gum input --password --header "Repeat passphrase")
[ "$p1" = "$p2" ] || die "Passphrases don't match."
[ -n "$p1" ] || die "Empty passphrase."
printf '%s' "$p1" > /tmp/disk.key

## 6. Point of no return
echo
gum confirm --default=false \
  "ERASE $disk and install '$host'? This destroys everything on the disk." \
  || { say "Aborted — nothing was touched."; exit 0; }

say "Partitioning $disk (disko)"
disko --mode destroy,format,mount --yes-wipe-all-disks --flake "$ND_DIR#$host"

say "Installing (first run downloads/compiles a lot)"
nixos-install --flake "$ND_DIR#$host" --no-root-passwd

say "Set the password for '$username'"
nixos-enter --root /mnt -c "passwd $username"

# The repo travels to the new home — including any generated host, so it
# can be committed and pushed from the installed system.
say "Copying the repo to the new home"
mkdir -p "/mnt/home/$username/work"
cp -r "$ND_DIR" "/mnt/home/$username/work/nd-dotfiles"
nixos-enter --root /mnt -c "chown -R $username /home/$username/work" || true

shred -u /tmp/disk.key 2>/dev/null || rm -f /tmp/disk.key
echo
say "${BOLD}Done.${RESET} After reboot: log in, run 'make' in ~/work/nd-dotfiles (dotfiles),"
say "and commit & push any generated host so this machine is reproducible."
gum confirm "Reboot now?" && reboot
